version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: tarjimon
    environment:
      POSTGRES_DB: tarjimon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
